version: '3.8'
services:
    NGINX:
        build: ./srcs/requirements/nginx/Dockerfile
        ports: "443:443"
        restart: always

    db:
        build: ./srcs/requirements/mariadb/Dockerfile
        ports: "3306:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWOR}
            MYSQL_USER=${MYSQL_USER}
            MYSQL_PASSWORD=${MYSQL_PASSWORD}


    wordpress:
        depends_on :
            - nginx
            - db
        build: ./srcs/requirements/wordpress/Dockerfile
        ports : "9000:9000"
        volumes:
            - /home/slescure/data/wordpress:/var/www/html

        restart: always
        environment:
            WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
            WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
            WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
            WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
